apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-k8s
  name: simple-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-k8s
  template:
    metadata:
      labels:
        app: simple-k8s
    spec:
      containers:
        - image: simple-k8s:latest
          imagePullPolicy: IfNotPresent
          name: simple-k8s
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-k8s-service
spec:
  selector:
    app: simple-k8s
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080 #container pod port